### ISSUE TITLE
Django static files not autodiscover

### ISSUE THREAD

**Issue by PabloLefort** [rhcarvalho/django-plus-falcon-pypy#1]
Hi, going with your example i finished up running the entire app with gunicorn only.

On develop, django app does not serve static files, unless execute `collectstatic`, because its not running with `pypy manage.py runserver`.

Any suggestions?

Thanks in advance

**Comment by rhcarvalho** [comment]
Hi @PabloLefort, sorry for the very long delay, I was not getting notifications for this repo.

If still relevant, what I have used in the past and would recommend for static files using pure-python is [WhiteNoise](http://whitenoise.evans.io/en/stable/).

Or you can also serve static files with any other webserver like [Apache httpd](https://httpd.apache.org/) or [nginx](http://nginx.org/en/) if you are already using them.

Official Django docs: https://docs.djangoproject.com/en/1.11/howto/static-files/deployment/
